<?php

namespace Front\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUserByProfileQueryBuilder($codeProfile) {
        $qb = $this->createQueryBuilder("user");
        return $qb->leftJoin("user.profiles", "profiles")
            ->leftJoin("user.group", "group")
            ->leftJoin("group.profiles", "group_profiles")
            ->where($qb->expr()->in("profiles.code", $codeProfile))
            ->orWhere($qb->expr()->in("group_profiles.code", $codeProfile))
            ->orderBy("user.surname", "ASC");
    }
}
