front_user_homepage:
    path:     /
    defaults: { _controller: FrontUserBundle:Default:index }

fos_user_security_login:
    path:    /login
    defaults: { _controller: FrontUserBundle:Security:login }

user_profile_show:
     path:    /profile
     defaults: { _controller: FrontUserBundle:Profile:show }

user_profile_edit:
     path:    /profile/edit
     defaults: { _controller: FrontUserBundle:Profile:edit }

user_profile_default_avatar:
    path:    /profile/default_avatar
    defaults: { _controller: FrontUserBundle:Profile:defaultAvatar}

user_change_password:
    path:    /profile/change-password
    defaults: { _controller: FrontUserBundle:ChangePassword:changePassword }