fos_user_security_login:
    path:    /login
    defaults: { _controller: FrontUserBundle:Security:login }
    methods: ["GET", "POST"]

user_change_password:
    path:    /profile/change-password
    defaults: { _controller: FrontUserBundle:ChangePassword:changePassword }
    methods: ["GET", "POST"]

fos_user_resetting_check_email:
    path:    /check-email
    defaults: { _controller: FrontUserBundle:Resetting:checkEmail }
    methods: ["GET", "POST"]
