parameters:
  interactive_login_listener.class:
    Front\UserBundle\EventListener\PasswordListener
services:
  password_listener:
    class: %interactive_login_listener.class%
    arguments:
      - "@fos_user.user_manager"
      - "@router"
    tags:
     - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }