front_documents:
    path:    /documents
    defaults: { _controller: FrontBundle:Main:documents }

front_news:
    path:     /news/{domain}
    defaults:
        _controller: FrontBundle:Main:news
        domain: "all"
    requirements:
        domain: "[a-zA-Z]*"

front_homepage:
    path:     /{domain}
    defaults:
        _controller: FrontBundle:Main:news
        domain: "all"