news_index:
    path:     /news/{domain}
    defaults:
        _controller: FrontBundle:News:index
        domain: "all"

documents_index:
    path:    /documents/{domain}
    defaults:
        _controller: FrontBundle:Documents:index
        domain: "all"

front_homepage:
    path:     /
    defaults:
        _controller: FrontBundle:News:index
        domain: "all"