news_index:
    path:     /news/{domain}
    defaults:
        _controller: FrontBundle:News:index
        domain: "all"

documents_index:
    path:    /documents/{domain}
    defaults:
        _controller: FrontBundle:Documents:index
        domain: "all"

application_index:
    path:    /application
    defaults:
        _controller: FrontBundle:Applications:index

front_homepage:
    path:     /
    defaults:
        _controller: FrontBundle:News:index
        domain: "all"