front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Main:news }

front_documents:
    path:    /documents
    defaults: { _controller: FrontBundle:Main:documents }

front_news:
    path:     /news
    defaults: { _controller: FrontBundle:Main:news }