front_documents:
    path:    /documents
    defaults: { _controller: FrontBundle:Main:documents }

news_index:
    path:     /news/{domain}
    defaults:
        _controller: FrontBundle:News:index
        domain: "all"
    requirements:
        domain: "[a-zA-Z]*"

front_homepage:
    path:     /{domain}
    defaults:
        _controller: FrontBundle:News:index
        domain: "all"