services:
#    statator_app.example:
#        class: Statator\AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    statator_app.menu_getter:
            class: Statator\AppBundle\Services\MenuGetter
            arguments: ["@security.authorization_checker"]