<?php

namespace Front\AppBundle\Repository;

/**
 * AgencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgencyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAgencies() {
        $queryBuilder = $this->createQueryBuilder('agency_repository')
            ->where('agency_repository.active = :active')
            ->setParameter('active', true);

        return $queryBuilder->getQuery()->getResult();
    }
}
