<?php

namespace Front\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationConnectionStatisticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationConnectionStatisticsRepository extends EntityRepository
{
}
