<?php

namespace Front\AppBundle\Repository;

use DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * ApplicationConnectionStatisticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationConnectionStatisticsRepository extends EntityRepository
{
    /**
     * Returns the number of users by months by application
     * @return array
     */
    public function getCountUserByApplication($month, $year) {
        return $this->createQueryBuilder("application_connection_statistics")
            ->select("COUNT(application_connection_statistics.user) as number_user, 
                        application.code as application_code")
            ->innerJoin("application_connection_statistics.application", "application")
            ->where("MONTH(application_connection_statistics.date) = :month")
            ->setParameter("month", $month)
            ->andWhere("YEAR(application_connection_statistics.date) = :year")
            ->setParameter("year", $year)
            ->groupBy("application_connection_statistics.application")
            ->orderBy("application.name")
            ->getQuery()
            ->getResult();
    }

    /**
     * Returns the values for $numberMonthsToReturn months for the browsers used in the app
     * @param $numberMonthsToReturn
     * @return array
     */
    public function getComparisonBrowser ($numberMonthsToReturn) {
        return $this->createQueryBuilder("application_connection_statistics")
            ->select("COUNT(application_connection_statistics.browser) as number_connection, 
                        application_connection_statistics.browser")
            ->where("application_connection_statistics.date > :date")
            ->setParameter("date", new DateTime('0:00 first day of -' . $numberMonthsToReturn . ' months'))
            ->groupBy("application_connection_statistics.browser")
            ->getQuery()
            ->getResult();
    }
}
