<?php

namespace Front\AppBundle\Repository;

use DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * ApplicationConnectionStatisticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationConnectionStatisticsRepository extends EntityRepository
{
    /**
     * Returns the number of users by months by application
     * @return array
     */
    public function getCountUserByApplication() {
        return $this->createQueryBuilder("application_connection_statistics")
            ->select("COUNT(application_connection_statistics.user) as number_user, 
                        application.name as application_name, 
                        MONTH(application_connection_statistics.date) as month, 
                        MONTHNAME(application_connection_statistics.date)")
            ->leftJoin("application_connection_statistics.application", "application")
            ->groupBy("application_connection_statistics.application")
            ->addGroupBy("month")
            ->orderBy("application.name")
            ->addOrderBy("month")
            ->getQuery()
            ->getResult();
    }

    /**
     * Returns the values for $numberMonthsToReturn months for the browsers used in the app
     * @param $numberMonthsToReturn
     * @return array
     */
    public function getComparisonBrowser ($numberMonthsToReturn) {
        return $this->createQueryBuilder("application_connection_statistics")
            ->select("COUNT(application_connection_statistics.browser) as number_connection, 
                        application_connection_statistics.browser")
            ->where("application_connection_statistics.date > :date")
            ->setParameter("date", new DateTime('0:00 first day of -' . $numberMonthsToReturn . ' months'))
            ->groupBy("application_connection_statistics.browser")
            ->getQuery()
            ->getResult();
    }
}
