<?php

namespace Front\AppBundle\Repository;

/**
 * ApplicationConnectionStatisticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationConnectionStatisticsRepository extends \Doctrine\ORM\EntityRepository
{
}
