<?php

namespace Front\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Front\AppBundle\Entity\ProfilePrefered;

/**
 * ProfilePreferedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilePreferedRepository extends EntityRepository
{
    /**
     * @param $idApplication
     * @param $idUser
     * @return ProfilePrefered
     */
    public function findByApplicationAndUser($idApplication, $idUser) {
        return $this->createQueryBuilder("profile_prefered_repository")
            ->join("profile_prefered_repository.application", "application")
            ->join("profile_prefered_repository.user", "user")
            ->where("application.id = :idApplication")
            ->setParameter("idApplication", $idApplication)
            ->andWhere("user.id = :idUser")
            ->setParameter("idUser", $idUser)
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult();
    }
}
