<?php

namespace Front\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{
    /**
     * Returns a QueryBuilder that returns every region that is active
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getActiveQueryBuilder() {
        return $this->createQueryBuilder("region_repository")
            ->where("region_repository.active = :active")
            ->setParameter("active", true);
    }
}
