<?php

namespace Front\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Front\AppBundle\Entity\Application;

/**
 * RightsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightRepository extends EntityRepository
{
    public function getQbByApplication(Application $application) {
        return $this->createQueryBuilder("right_repository")
            ->leftJoin("right_repository.application", "application")
            ->where("application.id = :idApplication")
            ->setParameter("idApplication", $application->getId());
    }
}
