imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@FrontAppBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        name: "%my.cookie.name%"
    fragments:       ~
    http_method_override: true
    assets: ~
    translator:    {fallback: ["%locale%"]}

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
            - 'bootstrap_3_layout.html.twig'
            - 'VichUploaderBundle:Form:fields.html.twig'
    globals:
        serverName: "%server.name%"
        applicationAdministration:  "%application.code.administration%"
        applicationDomain:          "%application.code.domain%"
        applicationHelpReferentiel: "%application.code.helpreferentiel%"
        applicationStatator:        "%application.code.statator%"

# Doctrine Configuration
doctrine:
    dbal:
        server_version: 5.7.9
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Front\UserBundle\Entity\User
    profile:
        form:
            type: Front\UserBundle\Form\Type\ProfileFormType
    from_email:
        address:    isidore@orexad.com
        sender_name:    Isidore2


vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            # I don't understand clearly how I have to create the good Path for here. The "Isidore2" part is not good
            # but I don't manage to change it
            uri_prefix:            '/../%application_name%/web/uploads/avatar'
            upload_destination:    '%kernel.root_dir%/../web/uploads/avatar'
            namer:                 vich_uploader.namer_origname

        news_image:
            uri_prefix:            '/../%application_name%/web/uploads/domain/news'
            upload_destination:    '%kernel.root_dir%/../web/uploads/domain/news'
            namer:                 vich_uploader.namer_origname

        news_file:
            uri_prefix:            '/../%application_name%/web/uploads/domain/newsFiles'
            upload_destination:    '%kernel.root_dir%/../web/uploads/domain/newsFiles'
            namer:                 vich_uploader.namer_origname

        document_file:
            uri_prefix:            '/../%application_name%/web/uploads/domain/frontDocuments'
            upload_destination:    '%kernel.root_dir%/../web/uploads/domain/frontDocuments'
            namer:                 vich_uploader.namer_origname

        catalog_file:
            uri_prefix:            '/../%application_name%/web/uploads/domain/catalog/file'
            upload_destination:    '%kernel.root_dir%/../web/uploads/domain/catalog/file'
            namer:                 vich_uploader.namer_origname

        catalog_image:
            uri_prefix:            '/../%application_name%/web/uploads/domain/catalog/image'
            upload_destination:    '%kernel.root_dir%/../web/uploads/domain/catalog/image'
            namer:                 vich_uploader.namer_origname

        application_image:
            uri_prefix:            /../isidore2/web/download/front/applications
            upload_destination:    '%kernel.root_dir%/../web/download/front/applications'
            namer:                 vich_uploader.namer_origname

ivory_ck_editor:
    configs:
        my_basic_config:
            toolbar: [ [ "Source", "-", "Cut", "Copy", 'Paste','PasteText','PasteFromWord','-','Undo','Redo' ],
             [ 'Link','Unlink','Anchor' ],
             [ 'Bold','Italic','Underline','Strike', 'Blockquote','Subscript','Superscript' ], "/",
             [ 'NumberedList','BulletedList','-','Outdent','Indent','-','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ],
             [ 'Styles', 'Format','Font','FontSize', '-', 'TextColor','BGColor' ], [ 'Maximize' ]]