help_referentiel_app:
    resource: "@HelpReferentielAppBundle/Resources/config/routing.yml"
    prefix:   /help_referentiel

front_domain:
    resource: "@FrontDomainBundle/Resources/config/routing.yml"
    prefix:   /

front_app:
    resource: "@FrontAppBundle/Resources/config/routing.yml"
    prefix:   /

front_user:
    resource: "@FrontUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_user_manager:
    resource: "@AdminUserManagerBundle/Resources/config/routing.yml"
    prefix:   /admin

admin_manager:
    resource: "@AdminAppBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
