front_app:
    resource: "@FrontAppBundle/Resources/config/routing.yml"
    prefix:   /

front_user:
    resource: "@FrontUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_user_manager:
    resource: "@AdminUserManagerBundle/Resources/config/routing.yml"
    prefix:   /admin
