# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    always_authenticate_before_granting: true
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        [IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY] # This is used in the admin to switch between users

        # Application "Administration Isidore 2"
        ROLE_ADMIN_USER_VIEW: [ROLE_USER, ROLE_ADMIN]
        ROLE_ADMIN_USER_UPDATE: ROLE_ADMIN_USER_VIEW
        ROLE_ADMIN_USER_ALLOWED_TO_SWITCH: [ROLE_ADMIN_USER_VIEW, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN_GROUP_VIEW: [ROLE_USER, ROLE_ADMIN]
        ROLE_ADMIN_GROUP_UPDATE: ROLE_ADMIN_GROUP_VIEW
        ROLE_ADMIN_APPLICATION_VIEW: [ROLE_USER, ROLE_ADMIN]
        ROLE_ADMIN_APPLICATION_UPDATE: ROLE_ADMIN_APPLICATION_VIEW
        ROLE_ADMIN_AGENCY_VIEW: [ROLE_USER, ROLE_ADMIN]
        ROLE_ADMIN_AGENCY_UPDATE: ROLE_ADMIN_AGENCY_VIEW
        ROLE_ADMIN_REGION_VIEW: [ROLE_USER, ROLE_ADMIN]
        ROLE_ADMIN_REGION_UPDATE: ROLE_ADMIN_REGION_VIEW
        ROLE_ADMIN_ZONE_VIEW: [ROLE_USER, ROLE_ADMIN]
        ROLE_ADMIN_ZONE_UPDATE: ROLE_ADMIN_ZONE_VIEW

        # Application "Gestion du portail web"
        ROLE_DOMAIN_BASE: [ROLE_USER, ROLE_DOMAIN_MANAGER]
        ROLE_DOMAIN_NEWS_DOCUMENT: ROLE_DOMAIN_BASE
        ROLE_DOMAIN_CATALOG: ROLE_DOMAIN_BASE
        ROLE_DOMAIN_ADMIN: [ROLE_DOMAIN_NEWS_DOCUMENT, ROLE_DOMAIN_CATALOG]


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id:    fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                check_path:     /login_check
                remember_me:    true
                csrf_token_generator: security.csrf.token_manager
                success_handler: front_userbundle.password_checker
            remember_me:
                secret: '%secret'
            logout:
                path:    /logout
                target:  /
            anonymous:    true
            switch_user: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/domain_manager/, role: ROLE_DOMAIN_BASE }