services:
#    admin_app.example:
#        class: Admin\AppBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    admin.menu_getter:
        class: Admin\AppBundle\Services\MenuGetter
        arguments: ["@security.authorization_checker"]
