<?php

namespace Front\DomainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CatalogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogRepository extends EntityRepository
{
    public function getFromSide($isLeft) {
        $qb = $this->createQueryBuilder("catalog_repository");

        return $qb->where("catalog_repository.isPositionLeft = :isLeft")
            ->setParameter("isLeft", $isLeft)
            ->andWhere("catalog_repository.beginPublicationDate < :today")
            ->setParameter("today", new \DateTime())
            ->orderBy("catalog_repository.beginPublicationDate", "DESC")
            ->getQuery()
            ->getResult();
    }
}
