<?php

namespace Front\DomainBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * newsDomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainRepository extends EntityRepository
{
    public function getActiveQueryBuilder() {
        $qb = $this->createQueryBuilder('domain_repository');
        return $qb
            ->where($qb->expr()->eq("domain_repository.active", true));
    }
}
