<?php

namespace Front\DomainBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * newsDomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainRepository extends EntityRepository
{
    public function getActiveQueryBuilder() {
        $qb = $this->createQueryBuilder('domain_repository');
        return $qb
            ->where($qb->expr()->eq("domain_repository.active", true));
    }

    /**
     * @param string $metadataClass
     * @return array
     */
    public function getActiveWithChildren($metadataClass) {
        $em = $this->getEntityManager();
        $qb = $this->createQueryBuilder('domain_repository');
        $qb->join("domain_repository.domainElements", "domain_elements")

            ->where("domain_elements.endPublicationDate >= :dateToday")
            ->orWhere($qb->expr()->isNull("domain_elements.endPublicationDate"))
            ->andWhere($qb->expr()->eq("domain_repository.active", true))
            ->andWhere("domain_elements.beginPublicationDate <= :dateToday")
            ->setParameter("dateToday", new \DateTime())
            ->andWhere("domain_elements INSTANCE OF :class")
            ->setParameter("class", $em->getClassMetadata($metadataClass))

            ->orderBy("domain_repository.label");

        return $qb
            ->getQuery()
            ->getResult();
    }
}
