<?php

namespace Front\DomainBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function getActiveNews($domain) {
        $qb = $this->createQueryBuilder("news_repository");
        if ($domain != "all") {
            $qb->where("domain.labelSimplified = :domain")
                ->setParameter("domain", $domain);
        }
        return $qb->andWhere("domain.active = :active")
            ->setParameter("active", true)
            ->andWhere("news_repository.beginPublicationDate <= :dateToday")
            ->andWhere("news_repository.endPublicationDate >= :dateToday")
            ->orWhere($qb->expr()->isNull("news_repository.endPublicationDate"))
            ->setParameter("dateToday", new \DateTime())
            ->leftJoin("news_repository.domain", "domain")
            ->orderBy("news_repository.creationDate", "DESC")
            ->getQuery()
            ->getResult();
    }
}
