<?php

namespace Front\DomainBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function getActiveNews($domain, $page, $nbPerPage) {
        $qb = $this->createQueryBuilder("news_repository")
            ->leftJoin("news_repository.domain", "domain");

        $qb->where("news_repository.endPublicationDate >= :dateToday")
            ->orWhere($qb->expr()->isNull("news_repository.endPublicationDate"));

        if ($domain != "all") {
            $qb->andWhere("domain.labelSimplified = :domain")
                ->setParameter("domain", $domain);
        }
        $query = $qb
            ->andWhere("domain.active = :active")
            ->setParameter("active", true)
            ->andWhere("news_repository.beginPublicationDate <= :dateToday")
            ->setParameter("dateToday", new \DateTime())

            ->orderBy("news_repository.beginPublicationDate", "DESC")
            ->getQuery();

        $query->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }
}
