<?php

namespace Front\DomainBundle\Repository;

/**
 * NewsFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsFileRepository extends \Doctrine\ORM\EntityRepository
{
}
