<?php

namespace Front\DomainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsFileRepository extends EntityRepository
{
}
