help_referentiel_app_homepage:
    path:     /
    defaults: { _controller: HelpReferentielAppBundle:Base:index }

help_referentiel_app_request_index:
    path:     /request
    defaults: { _controller: HelpReferentielAppBundle:Request:index }