services:
#    help_referentiel_app.example:
#        class: HelpReferentiel\AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    _defaults:
        autowire: true
        autoconfigure: true

    help_referentiel_app.menu_getter:
        class: HelpReferentiel\AppBundle\Services\MenuGetter
        arguments: ["@security.authorization_checker", "@router"]

    help_referentiel_app.twig_extension:
        class: HelpReferentiel\AppBundle\Twig\HelpReferentielAppTwigExtension
        public: false
        arguments: ['@help_referentiel_app.menu_getter']
        tags:
            - { name: twig.extension }
