news_view:
    path:    /news/view/{id}
    defaults:
        _controller: FrontDomainBundle:News:view

news_index:
    path:     /news/{domain}/{page}
    defaults:
        _controller: FrontDomainBundle:News:index
        page:        1
        domain:      "all"
    requirements:
        page:    \d*

documents_index:
    path:    /documents/{domain}
    defaults:
        _controller: FrontDomainBundle:Documents:index
        domain: "all"

domain_manager_index:
    path:    /domain_manager
    defaults:
        _controller: FrontDomainBundle:App:index

domain_manager_news:
    path:    /domain_manager/news
    defaults:
        _controller: FrontDomainBundle:News:list

domain_manager_add_news:
    path:    /domain_manager/news/add
    defaults:
        _controller: FrontDomainBundle:News:add

domain_manager_modify_news:
    path:    /domain_manager/news/modify/{id}
    defaults:
        _controller: FrontDomainBundle:News:modify

domain_manager_document:
    path:    /domain_manager/document
    defaults:
        _controller: FrontDomainBundle:App:document