news_view:
    path:    /news/view/{id}
    defaults:
        _controller: FrontDomainBundle:News:view

news_index:
    path:     /news/{domain}
    defaults:
        _controller: FrontDomainBundle:News:index
        domain: "all"

documents_index:
    path:    /documents/{domain}
    defaults:
        _controller: FrontDomainBundle:Documents:index
        domain: "all"