application_index:
    path:    /applications
    defaults:
        _controller: FrontAppBundle:Applications:index

application_external_access:
    path:    /applications/external_access/{applicationId}
    defaults:
        _controller: FrontAppBundle:Applications:externalAccess

front_homepage:
    path:     /
    defaults:
        _controller: FrontDomainBundle:News:index
        domain: "all"

users_admin:
    path:    /adminIsidore/users
    defaults:
        _controller: FrontAppBundle:Admin:user