news_index:
    path:     /news/{domain}
    defaults:
        _controller: FronFrontAppBundle:News:index
        domain: "all"

documents_index:
    path:    /documents/{domain}
    defaults:
        _controller: FrontAppBundle:Documents:index
        domain: "all"

application_index:
    path:    /applications
    defaults:
        _controller: FrontAppBundle:Applications:index

front_homepage:
    path:     /
    defaults:
        _controller: FrontAppBundle:News:index
        domain: "all"

users_admin:
    path:    /adminIsidore/users
    defaults:
        _controller: FrontAppBundle:Admin:user