services:
#    front_app.example:
#        class: Front\AppBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    frontapp.twig_extension:
        class: Front\AppBundle\Twig\FrontAppTwigExtension
        public: false
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']
        tags:
            - { name: twig.extension }