services:
#    front_app.example:
#        class: Front\AppBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    frontapp.twig_extension:
        class: Front\AppBundle\Twig\FrontAppTwigExtension
        public: false
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']
        tags:
            - { name: twig.extension }

    frontapp.application_getter:
        class: Front\AppBundle\Services\ApplicationGetter
        arguments: ["@doctrine.orm.entity_manager"]

    frontapp.right_checker:
        class: Front\AppBundle\Services\RightChecker

    frontapp.application_connection_statistics:
        class: Front\AppBundle\Services\ApplicationConnectionLogger
        arguments: ["@doctrine.orm.entity_manager"]