services:
#    front_app.example:
#        class: Front\AppBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    _defaults:
        autowire: true
        autoconfigure: true

    frontapp.twig_extension:
        class: Front\AppBundle\Twig\FrontAppTwigExtension
        public: false
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@front_app.menu_getter']
        tags:
            - { name: twig.extension }

    frontapp.application_getter:
        class: Front\AppBundle\Services\ApplicationGetter
        arguments: ["@doctrine.orm.entity_manager", "@session.flash_bag", "%application.code.helpinfo%"]

    frontapp.right_checker:
        class: Front\AppBundle\Services\RightChecker

    frontapp.application_connection_statistics:
        class: Front\AppBundle\Services\ApplicationConnectionLogger
        arguments: ["@doctrine.orm.entity_manager"]

    front_app.menu_getter:
        class: Front\AppBundle\Services\MenuGetter
        arguments: ["@security.authorization_checker", "@router"]

    front_app.beta.html_adder:
        class: Front\AppBundle\Services\Beta\BetaHtmlAdder

    front_app.beta.listener:
        class: Front\AppBundle\Services\Beta\BetaListener
        arguments: [ "@front_app.beta.html_adder", "%environment%"]
        tags:
            - { name: kernel.event_listener, event: kernel.response,  method: processBeta }
