services:
#    front_app.example:
#        class: Front\AppBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    front_bundle.last_route_event_listener:
        class: Front\AppBundle\EventListener\LastRouteListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 30 }