admin_user_manager_homepage:
    path:     /users
    defaults: { _controller: AdminUserManagerBundle:User:index }

admin_user_manager_create:
    path:     /user/add
    defaults: { _controller: AdminUserManagerBundle:User:create }

admin_user_manager_update:
    path:     /user/{idUser}
    requirements:
        id: \d+
    defaults: { _controller: AdminUserManagerBundle:User:updateBase }

admin_user_agency_update:
    path:    /user/ajax/agency/update
    defaults: { _controller: AdminUserManagerBundle:User:updateAgencyAjax }
    options:
        expose: true
    condition: "request.isXmlHttpRequest()"
    methods: [POST]